"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { getHistory, type DiagnosticEntry } from "@/app/lib/history";

// ── Label maps (mirrors intake-config values) ─────────────────────────────────

const COMPLAINT_LABELS: Record<string, string> = {
  no_cooling:    "No cooling",
  no_heating:    "No heating",
  wont_start:    "System won't come on",
  short_cycling: "Short cycling",
  unusual_noise: "Unusual noise",
  poor_airflow:  "Weak or no airflow",
};

const SYSTEM_LABELS: Record<string, string> = {
  split_ac:       "Split system AC",
  heat_pump:      "Heat pump",
  gas_furnace_ac: "Gas furnace + AC",
  package_unit:   "Package unit",
  mini_split:     "Mini-split / ductless",
  not_sure:       "Not yet identified",
};

const AGE_LABELS: Record<string, string> = {
  under_2:  "Under 2 years",
  "2_to_5": "2–5 years",
  "5_to_10":"5–10 years",
  "10_to_15":"10–15 years",
  over_15:  "15+ years",
  unknown:  "Unknown",
};

const SEVERITY_LABELS: Record<string, { label: string; color: string }> = {
  critical: { label: "CRITICAL — Safety hazard. Address immediately.", color: "#dc2626" },
  high:     { label: "HIGH — System is down. Needs repair now.",        color: "#ea580c" },
  medium:   { label: "MEDIUM — Performance degraded. Should be addressed.", color: "#ca8a04" },
  low:      { label: "LOW — Minor issue. Schedule when convenient.",    color: "#16a34a" },
};

const CONFIDENCE_LABELS: Record<string, string> = {
  high:   "High",
  medium: "Medium",
  low:    "Low",
};

// ── Types ─────────────────────────────────────────────────────────────────────

interface DiagnosticResult {
  headline: string;
  severity: string;
  system_area: string;
  what_was_detected: string;
  likely_causes: string[];
  based_on_your_answers: string;
  safety_flags: string[];
  confidence: string;
}

type Answers = Record<string, string | string[]>;

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    weekday: "long",
    month:   "long",
    day:     "numeric",
    year:    "numeric",
    hour:    "numeric",
    minute:  "2-digit",
    hour12:  true,
  });
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function ReportPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const router = useRouter();
  const [entry, setEntry] = useState<DiagnosticEntry | null>(null);
  const [missing, setMissing] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const found = getHistory().find((e) => e.id === Number(id)) ?? null;
    if (!found) setMissing(true);
    else setEntry(found);
  }, [id]);

  async function handleDownloadPDF() {
    if (!reportRef.current) return;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const html2pdf = (await import("html2pdf.js")).default as any;
    html2pdf(reportRef.current, {
      margin:   [10, 10, 10, 10],
      filename: `HVAC-Diagnostic-Report-${id}.pdf`,
      image:    { type: "jpeg", quality: 0.97 },
      html2canvas:  { scale: 2, useCORS: true },
      jsPDF:    { unit: "mm", format: "a4", orientation: "portrait" },
    });
  }

  function handleEmail(result: DiagnosticResult, complaint: string) {
    const subject = encodeURIComponent(`HVAC Diagnostic Report - ${result.headline}`);
    const causes = result.likely_causes.slice(0, 2)
      .map((c, i) => `${i + 1}. ${c}`)
      .join("\n");
    const sevLabel = (SEVERITY_LABELS[result.severity]?.label ?? result.severity).split(" — ")[0];
    const body = encodeURIComponent(
      `HVAC Diagnostic Report\n` +
      `${"-".repeat(30)}\n\n` +
      `Complaint:  ${complaint}\n` +
      `Headline:   ${result.headline}\n` +
      `Severity:   ${sevLabel}\n\n` +
      `Potential Failure Points:\n${causes}\n\n` +
      `Generated by HVAC Diagnostic Agent`
    );
    const mailtoUrl = `mailto:?subject=${subject}&body=${body}`;
    console.log(mailtoUrl);
    window.location.href = mailtoUrl;
  }

  if (missing) {
    return (
      <div style={{ fontFamily: "system-ui, sans-serif", padding: 40, textAlign: "center" }}>
        <p style={{ color: "#555", marginBottom: 20 }}>Report not found.</p>
        <a href="/history" style={{ color: "#2563eb" }}>Back to History</a>
      </div>
    );
  }

  if (!entry) return null;

  const result  = entry.result  as DiagnosticResult;
  const answers = entry.answers as Answers;

  const complaint   = COMPLAINT_LABELS[answers?.complaint as string]   ?? answers?.complaint ?? "—";
  const systemType  = SYSTEM_LABELS[answers?.system_type as string]    ?? answers?.system_type ?? "—";
  const unitAge     = AGE_LABELS[answers?.unit_age as string]          ?? answers?.unit_age ?? "—";
  const confidence  = CONFIDENCE_LABELS[result.confidence]             ?? result.confidence;
  const sevConfig   = SEVERITY_LABELS[result.severity]                 ?? { label: result.severity, color: "#555" };

  const s: Record<string, React.CSSProperties> = {
    page: {
      fontFamily: "'Segoe UI', system-ui, Arial, sans-serif",
      backgroundColor: "#fff",
      color: "#111",
      maxWidth: 720,
      margin: "0 auto",
      padding: "40px 32px 64px",
      lineHeight: 1.5,
    },
    topBar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 32,
      paddingBottom: 16,
      borderBottom: "2px solid #e5e7eb",
    },
    backBtn: {
      background: "none",
      border: "none",
      cursor: "pointer",
      color: "#2563eb",
      fontSize: 14,
      fontWeight: 600,
      padding: 0,
      display: "flex",
      alignItems: "center",
      gap: 4,
    },
    downloadBtn: {
      background: "#5d9cf5",
      border: "none",
      cursor: "pointer",
      color: "#fff",
      fontSize: 13,
      fontWeight: 600,
      padding: "8px 16px",
      borderRadius: 8,
    },
    emailBtn: {
      background: "transparent",
      border: "1.5px solid #5d9cf5",
      cursor: "pointer",
      color: "#5d9cf5",
      fontSize: 13,
      fontWeight: 600,
      padding: "8px 16px",
      borderRadius: 8,
    },
    title: {
      fontSize: 26,
      fontWeight: 700,
      color: "#111",
      marginBottom: 4,
    },
    subtitle: {
      fontSize: 13,
      color: "#6b7280",
      marginBottom: 32,
    },
    section: {
      marginBottom: 28,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: 700,
      letterSpacing: "0.1em",
      textTransform: "uppercase" as const,
      color: "#6b7280",
      marginBottom: 10,
    },
    card: {
      border: "1px solid #e5e7eb",
      borderRadius: 10,
      padding: "16px 20px",
      backgroundColor: "#f9fafb",
    },
    row: {
      display: "flex",
      gap: 8,
      marginBottom: 6,
    },
    label: {
      fontSize: 13,
      color: "#6b7280",
      minWidth: 110,
      flexShrink: 0,
    },
    value: {
      fontSize: 13,
      color: "#111",
      fontWeight: 500,
    },
    headline: {
      fontSize: 18,
      fontWeight: 700,
      color: "#111",
      marginBottom: 8,
    },
    body: {
      fontSize: 14,
      color: "#374151",
      marginBottom: 8,
    },
    small: {
      fontSize: 13,
      color: "#6b7280",
    },
    divider: {
      height: 1,
      backgroundColor: "#e5e7eb",
      margin: "16px 0",
    },
    causeNum: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: 22,
      height: 22,
      borderRadius: "50%",
      backgroundColor: "#dbeafe",
      color: "#2563eb",
      fontSize: 12,
      fontWeight: 700,
      flexShrink: 0,
      marginTop: 1,
    },
    sevBadge: {
      display: "inline-block",
      border: `2px solid ${sevConfig.color}`,
      color: sevConfig.color,
      borderRadius: 6,
      padding: "3px 12px",
      fontSize: 13,
      fontWeight: 700,
      letterSpacing: "0.08em",
      marginBottom: 8,
    },
    flag: {
      fontSize: 13,
      color: "#dc2626",
      marginBottom: 4,
    },
    footer: {
      marginTop: 48,
      paddingTop: 16,
      borderTop: "1px solid #e5e7eb",
      fontSize: 12,
      color: "#9ca3af",
      textAlign: "center" as const,
    },
  };

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { margin: 0; }
        }
      `}</style>

      <div style={s.page}>
        {/* ── Top bar ── */}
        <div style={s.topBar} className="no-print">
          <button style={s.backBtn} onClick={() => router.back()}>
            ← Back
          </button>
          <div style={{ display: "flex", gap: 10 }}>
            <button style={s.emailBtn} onClick={() => handleEmail(result, complaint)}>
              Email Report
            </button>
            <button style={s.downloadBtn} onClick={handleDownloadPDF}>
              Download PDF
            </button>
          </div>
        </div>

        {/* ── Printable report content ── */}
        <div ref={reportRef}>

        {/* ── Report header ── */}
        <div style={s.section}>
          <div style={s.title}>HVAC Diagnostic Report</div>
          <div style={s.subtitle}>{formatDate(entry.timestamp)}</div>
        </div>

        {/* ── System info ── */}
        <div style={s.section}>
          <div style={s.sectionTitle}>System Information</div>
          <div style={s.card}>
            <div style={s.row}>
              <span style={s.label}>Complaint</span>
              <span style={s.value}>{complaint}</span>
            </div>
            <div style={s.row}>
              <span style={s.label}>System type</span>
              <span style={s.value}>{systemType}</span>
            </div>
            <div style={s.row}>
              <span style={s.label}>Unit age</span>
              <span style={s.value}>{unitAge}</span>
            </div>
            <div style={{ ...s.row, marginBottom: 0 }}>
              <span style={s.label}>Confidence</span>
              <span style={s.value}>{confidence}</span>
            </div>
          </div>
        </div>

        {/* ── Potential failure points ── */}
        <div style={s.section}>
          <div style={s.sectionTitle}>Potential Failure Points</div>
          <div style={s.card}>
            {result.likely_causes.slice(0, 2).map((cause, i) => (
              <div key={i} style={{ display: "flex", gap: 12, marginBottom: i < 1 ? 12 : 0 }}>
                <span style={s.causeNum}>{i + 1}</span>
                <span style={{ fontSize: 14, color: "#374151" }}>{cause}</span>
              </div>
            ))}
          </div>
        </div>

        {/* ── Summary ── */}
        <div style={s.section}>
          <div style={s.sectionTitle}>Summary</div>
          <div style={s.card}>
            <div style={s.headline}>{result.headline}</div>
            <div style={s.body}>{result.what_was_detected}</div>
            <div style={s.small}>{result.system_area}</div>

            <div style={s.divider} />

            <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#6b7280", marginBottom: 6 }}>
              Assessment
            </div>
            <div style={s.sevBadge}>{sevConfig.label.split(" — ")[0]}</div>
            <div style={{ fontSize: 13, color: sevConfig.color, marginBottom: result.safety_flags.length > 0 ? 10 : 0 }}>
              {sevConfig.label.split(" — ")[1]}
            </div>

            {result.safety_flags.length > 0 && (
              <>
                {result.safety_flags.map((flag, i) => (
                  <div key={i} style={s.flag}>⚠ {flag}</div>
                ))}
              </>
            )}
          </div>
        </div>

        {/* ── Based on your answers ── */}
        <div style={s.section}>
          <div style={s.sectionTitle}>Based on Technician Input</div>
          <div style={s.card}>
            <div style={{ fontSize: 14, color: "#374151" }}>{result.based_on_your_answers}</div>
          </div>
        </div>

        {/* ── Footer ── */}
        <div style={s.footer}>
          Generated by HVAC Diagnostic Agent &nbsp;·&nbsp; {new Date(entry.timestamp).getFullYear()}
        </div>

        </div>{/* end reportRef */}
      </div>
    </>
  );
}
